app/core/urls.py
from django.urls import path
from . import views

app_name = 'core'
urlpatterns = [
    path('', views.index_view, name='index'),
    path('register', views.register_view, name='register'),
    path('recipes', views.recipes_view, name='recipes'),
    path('recipe/approve', views.recipe_approve_view, name='approve_recipe'),
    path('recipe/create', views.create_recipe_view, name='create_recipe'),
    path('recipe_details/<int:pk>', views.recipes_details, name='recipe_details'),
    path('recipe/approve/<int:pk>', views.recipe_details_approve_view, name='recipe_details_approve'),
    path('recipe/delete/<int:pk>', views.recipe_delete_view, name='recipe_confirm_delete'),
    path('recipe/favourite/<int:pk>', views.recipe_add_to_favourites_view, name='favorite_recipe'),
    path('recipe/favourites', views.favourite_recipes_view, name='favourites'),
]

app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('', include('app.core.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/core/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.core.validators import MinLengthValidator, MaxValueValidator, MinValueValidator
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Recipe(models.Model):
    name = models.CharField("Name", max_length=128, validators=[MinLengthValidator(2)])
    time = models.PositiveSmallIntegerField("Time", validators=[MaxValueValidator(2000),
                                                                MinValueValidator(1)])
    image = models.ImageField(null=True, blank=True)
    ingredients = models.TextField()
    directions = models.TextField()
    is_approved = models.BooleanField("Is approved", default=False)
    favourite = models.ManyToManyField(get_user_model(), related_name='favorite', blank=True)

    def __str__(self):
        return self.name


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

app/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import ModelForm
from .models import Recipe


class RegisterForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text="Optional.", label="First name")
    last_name = forms.CharField(max_length=30, required=False, help_text="Optional.", label="Last name")
    email = forms.EmailField(max_length=64)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')


class CreateRecipeForm(ModelForm):

    class Meta:
        model = Recipe
        fields = "__all__"
        exclude = ['is_approved', 'favourite']

app/core/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.views.generic import FormView, ListView, CreateView, DetailView, UpdateView, DeleteView
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from .forms import RegisterForm, CreateRecipeForm
from .mixins import AdminStaffRequiredMixin
from .models import Recipe


class IndexView(ListView):
    """ Index view """
    model = Recipe
    template_name = "core/index.html"

    def get_queryset(self):
        return Recipe.objects.all()


index_view = IndexView.as_view()


class RecipeApproveView(AdminStaffRequiredMixin, ListView):
    """ Approve recipe view """
    model = Recipe
    template_name = "core/recipe_approve.html"

    def get_queryset(self):
        return Recipe.objects.all()


recipe_approve_view = RecipeApproveView.as_view()


class RegisterView(FormView):
    """ Register form """
    template_name = 'registration/register.html'
    model = User
    form_class = RegisterForm
    success_url = reverse_lazy('core:index')

    def post(self, request, *args, **kwargs):
        response = super(RegisterView, self).post(request, *args, **kwargs)
        if response:
            form = self.get_form()
            form.save()
        return response


register_view = RegisterView.as_view()


class LoginView(FormView):
    """ Login form """
    template_name = 'registration/login.html'
    model = User
    form_class = RegisterForm
    success_url = reverse_lazy('core:index')

    def post(self, request, *args, **kwargs):
        response = super(LoginView, self).post(request, *args, **kwargs)
        if response:
            form = self.get_form()
            form.save()
        return response


register_view = RegisterView.as_view()


class RecipesView(ListView):
    """ Recipe list view """
    model = Recipe


recipes_view = RecipesView.as_view()


class RecipeDetailsView(DetailView):
    """ Recipe details view """
    template_name = 'core/recipe_details.html'
    model = Recipe


recipes_details = RecipeDetailsView.as_view()


class CreateRecipeView(LoginRequiredMixin, CreateView):
    """ Create author view """
    model = Recipe
    success_url = reverse_lazy('core:index')
    form_class = CreateRecipeForm
    login_url = reverse_lazy('login')


create_recipe_view = CreateRecipeView.as_view()


class DetailsRecipeApproveView(UpdateView):
    """Update recipe view """
    model = Recipe
    fields = ['name', 'time', 'image', 'ingredients', 'directions', 'is_approved']

    success_url = reverse_lazy('core:approve_recipe')


recipe_details_approve_view = DetailsRecipeApproveView.as_view()


class RecipeDeleteView(DeleteView):
    """ Delete recipe view """
    model = Recipe
    success_url = reverse_lazy('core:approve_recipe')


recipe_delete_view = RecipeDeleteView.as_view()


class RecipeAddToFavourites(LoginRequiredMixin, UpdateView):
    """ Add to favourites view """
    http_method_names = ['post', ]
    model = Recipe
    login_url = reverse_lazy('login')
    success_url = reverse_lazy('core:index')

    def post(self, *args, **kwargs):
        self.object = self.get_object()
        if self.object.favourite.filter(id=self.request.user.id).exists():
            self.object.favourite.remove(self.request.user)
        else:
            self.object.favourite.add(self.request.user)

        return redirect('core:recipe_details', pk=self.object.pk)


recipe_add_to_favourites_view = RecipeAddToFavourites.as_view()


class FavouriteRecipesView(LoginRequiredMixin, ListView):
    """Favourite list view"""
    model = Recipe
    template_name = "core/recipe_favourites.html"
    login_url = reverse_lazy('login')

    def get_queryset(self):
        return Recipe.objects.filter(favourite=self.request.user.id)


favourite_recipes_view = FavouriteRecipesView.as_view()

app/core/templates/core/base.html
{% extends 'bootstrap4/bootstrap4.html' %}
{% load static %}

{% load bootstrap4%}

{% block bootstrap4_title %}
CookIt
{% endblock %}

{% block bootstrap4_extra_head %}
    {% bootstrap_javascript jquery='full' %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/site.css' %}">

{% endblock %}


{% block bootstrap4_before_content %}
  {% include 'core/navbar.html' %}
{% endblock %}

{% block bootstrap4_content %}
    {% block content %}
    {% endblock %}
{% endblock %}

{% block bootstrap4_after_content %}

{% endblock %}

app/core/templates/core/index.html
{% extends 'core/base.html' %}
{% load static %}


{% block content %}

<div class="container">

    <div class="card-deck">

        {% for recipe in object_list %}
        {% if recipe.is_approved == True %}

            <div class="card m-3" style="min-width: 18rem; max-width: 30.5%;">
                <div class="card-header">
                    <h3>{{recipe.name}}<span class="float-right"><h3>{{recipe.time}} min </h3></span></h3>
                </div>
                <img src="{% static 'media/' %}{{recipe.image}}" class = " card-img-top imageThumbnail "/>
                <div class="card-footer text-center">


                    <form method="post" action="{% url 'core:favorite_recipe' recipe.id %}">
                         <a href="{% url 'core:recipe_details' recipe.id  %}" class="btn btn-primary">View Details</a>
                        {% csrf_token %}
                        <input type='hidden' name='recipe' value={{recipe.id}}>
                        <button type="submit"class="btn btn-success ">Add to favourites</button>

                    </form>
                </div>

            </div>
        {% endif %}
        {% endfor %}

    </div>


</div>
{% endblock %}

app/core/templates/core/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'core:index' %}">CookIt</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse"
          data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false"
          aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'core:favourites' %}">Favourites</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'core:create_recipe' %}">Add recipe</a>
      </li>
      {% if request.user.is_superuser %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'core:approve_recipe' %}">Approve recipes</a>
      </li>
      {% endif %}
    </ul>

    <ul class="navbar-nav ml-auto">
      {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Logout ({{ request.user.username }})</a>
        </li>
        <li>
          <a class="nav-link" href="{% url 'password_change' %}">Change Password</a>
        </li>
      {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'core:register' %}">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'login' %}">Login</a>
        </li>
      {% endif %}
    </ul>
  </div>
</nav>

app/core/templates/core/recipe_approve.html
{% extends 'core/base.html' %}
{% load static %}


{% block content %}

<div class="container">

    <div class="card-deck">

        {% for recipe in object_list %}


            <div class="card m-3" style="min-width: 18rem; max-width: 30.5%;">
                <div class="card-header">
                     <h3>{{recipe.name}}<span class="float-right"><h3>{{recipe.time}} min </h3></span></h3>
                </div>
                <img src="{% static 'media/' %}{{recipe.image}}" class = " card-img-top imageThumbnail "/>
                <div class="card-footer text-center">

                    <a href="{% url 'core:recipe_details' recipe.id  %}" class="btn btn-primary">View Details</a>
                    {% if recipe.is_approved == False %}
                    <a href = "{% url 'core:recipe_details_approve' recipe.id  %} " class="btn btn-success">Approve</a>
                    {% endif %}
                    <a href = "{% url 'core:recipe_confirm_delete' recipe.id  %} " class="btn btn-danger">Delete</a>
                </div>

            </div>

        {% endfor %}

    </div>


</div>
{% endblock %}

app/core/templates/core/recipe_confirm_delete.html
{% extends 'core/base.html' %}

{% load bootstrap4 %}

{% block content %}
<div class="container">
<form method="post">{% csrf_token %}
    <h2>Are you sure you want to delete "{{ object }}"?</h2>
    <input type="submit" class="btn btn-primary" value="Confirm">
</form>
</div>
{% endblock %}

app/core/templates/core/recipe_details.html
{% extends 'core/base.html' %}
{% load static %}
{% load bootstrap4 %}
{% block content %}
<div class="row justify-content-center m-3">
    <div class="col-sm-3">
        <div class="card">
            <div class="card-header">
                <h1>{{object.name}}<span class="float-right"><h3>{{recipe.time}} min </h3></span></h1>
            </div>
            <div class="card-body text-center">
                <img class="card-img-top imageThumbnail" src="{% static 'media/' %}{{recipe.image}}"  />
                <pre><h4>Ingredients:
{{object.ingredients}}</h4></pre>
            </div>
            <div class="card-body text-center">
                <pre><h4>Directions:
{{object.directions}}</h4></pre>
            </div>
            <div class="card-footer text-center">
                <a href="{% url 'core:index' %}" class="btn btn-primary" style="width:120px">Back</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/core/templates/core/recipe_details_approve.html
{% extends 'core/base.html' %}
{% load bootstrap4 %}
{% block content %}
{% endblock %}

app/core/templates/core/recipe_favourites.html
{% extends 'core/base.html' %}
{% load static %}


{% block content %}

<div class="container">

    <div class="card-deck">

        {% for recipe in object_list %}

            <div class="card m-3" style="min-width: 18rem; max-width: 30.5%;">
                <div class="card-header">
                    <h3>{{recipe.name}}<span class="float-right"><h3>{{recipe.time}} min </h3></span></h3>
                </div>
                <img src="{% static 'media/' %}{{recipe.image}}" class = " card-img-top imageThumbnail "/>
                <div class="card-footer text-center">


                    <form method="post" action="{% url 'core:favorite_recipe' recipe.id %}">
                        <a href="{% url 'core:recipe_details' recipe.id  %}" class="btn btn-primary">View Details</a>
                        {% csrf_token %}
                        <input type='hidden' name='recipe' value={{recipe.id}}>
                        <button type="submit"class="btn btn-danger ">Remove </button>
                    </form>
                </div>

            </div>
        {% endfor %}

    </div>


</div>
{% endblock %}

app/core/templates/core/recipe_form.html
{% extends 'core/base.html' %}

{% load bootstrap4 %}

{% block content %}
<div class="container">
    <form class="form" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% bootstrap_button "Save" button_type="submit" button_class="btn-primary" %}
        <a href="{% url 'core:index' %}" class="btn btn-light">Cancel</a>
    </form>
</div>
{% endblock %}